djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('', include('mainPage.urls')),
]

mainPage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='mainPage-home'),
    path('teacher/<slug:teacher_id>/<int:choice>/Classes/', views.t_clas, name='t_clas'),
    path('teacher/<int:ass_id>/attendance/', views.attendance_t, name='attendance_t'),
    path('teacher/<int:ass_id>/edit_attendance/', views.t_edit_attendance, name='t_edit_attendance'),
    path('teacher/<slug:ass_id>/attendance/submit/', views.t_submit, name='submit_t'),
    path('student/<slug:stud_id>/attendance/', views.attendance, name='attendance'),
    path('about/', views.about, name='mainPage-about'),
    # path('teacher/<int:assign_id>/Extra_class/', views.attendance_t, name='attendance_t'),
    path('table/', views.table, name='table'),
]

mainPage/models.py
from django.db import models

users/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser

import users


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        else:
            return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        else:
            return False


class Classes(models.Model):
    id = models.CharField(primary_key='True', max_length=50)

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        return self.id


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    fullName = models.CharField(max_length=200)
    class_id = models.ForeignKey(Classes, on_delete=models.CASCADE, default=1)
    username = models.CharField(primary_key='True', max_length=100)

    def __str__(self):
        return self.fullName


class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    fullName = models.CharField(max_length=200)
    username = models.CharField(primary_key='True', max_length=100)

    def __str__(self):
        return self.fullName


class Teaches(models.Model):
    classes = models.ForeignKey(Classes, on_delete=models.CASCADE)
    taughtBy = models.ForeignKey(Instructor, on_delete=models.CASCADE)

    def __str__(self):
        classesIn = Classes.objects.get(id=self.classes_id)
        teachersIn = Instructor.objects.get(username=self.taughtBy_id)
        return '%s : %s' % (classesIn.id, teachersIn.username)

class TeachesWithDate(models.Model):
    assign = models.ForeignKey(Teaches, on_delete=models.CASCADE)
    date = models.DateField()
    latenessStatus = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'


class Attendance(models.Model):
    course = models.ForeignKey(Classes, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(TeachesWithDate, on_delete=models.CASCADE, default=1)
    date = models.DateField(default='2018-10-23')
    status = models.IntegerField(default=0)

    def __str__(self):
        sname = Student.objects.get(username=self.student.username)
        cname = Classes.objects.get(id=self.course.id)
        return '%s : %s' % (sname.fullName, cname.id)

mainPage/views.py
from django.contrib.auth.decorators import login_required
from django.http import request
from django.shortcuts import render, get_object_or_404
from django.core import serializers
from users.models import User, Instructor, Classes, Student, Attendance, TeachesWithDate, Teaches

posts = [
    {
        'user': 'Javad',
        'title': 'Post',
        'content': 'Hello',
        'date_posted': '19/09'
    },
    {
        'user': 'Javid',
        'title': 'Post 2',
        'content': 'Hi',
        'date_posted': '20/09'
    }
]

@login_required(login_url='login/')
def home(request):
    acc = User.objects.get(username=request.user.username)
    print(acc.is_student)
    if acc.is_student:
        return render(request, 'mainPage/home.html')
    else:
        return render(request, 'mainPage/home_for_teach.html')


@login_required()
def about(request):
    return render(request, 'mainPage/about.html')

@login_required()
def table(request):
    system = request.POST.get('system',None)
    classes = Classes.objects.get(ClassChoice=system)
    context = {
        'system': classes.RegisteredStudents.all()
    }

    return render(request, 'mainPage/table.html', context)

@login_required()
def attendance(request, stud_id):
    student = get_object_or_404(Student, username=stud_id)
    att_list = Attendance.objects.filter(student=student).order_by('date')

    # print(att_list.last().status)

    return render(request, 'mainPage/table.html', {'att_list': att_list})


def attendance_t(request, ass_id):
    ass = get_object_or_404(Teaches, id=ass_id)
    classes_taught = ass.classes
    context = {
        'ass': ass,
        'classes_taught': classes_taught,
    }
    print(ass)
    # for s in classes_taught.student_set.all():
    #     print(s)
    # print(classes_taught.student_set.all())
    return render(request, 'mainPage/teacher_attendance_new_class.html',context)


def t_clas(request, teacher_id, choice):
    print(teacher_id)
    person = get_object_or_404(User, username=teacher_id)
    teacher = get_object_or_404(Instructor, user=person)
    return render(request, 'mainPage/class_choice.html', {'teacher': teacher,
                                                          'choice': choice
                                                          })


def t_submit(request, ass_id):
    ass = get_object_or_404(Teaches, id=ass_id)
    cl = ass.classes
    cr = ass.classes_id
    assc = ass.teacheswithdate_set.create(latenessStatus=1, date=request.POST['date'])
    assc.save()

    for i, s in enumerate(cl.student_set.all()):
        status = request.POST[s.username]
        if status == 'present':
            status = 0
        elif status == 'absent':
            status = 1
        else:
            status = 2
        date = request.POST['date']
        a = Attendance(course=cl, student=s, status=status, date=date, attendanceclass=assc)
        a.save()


    return render(request, 'mainPage/about.html')


def t_edit_attendance(request, ass_id):
    print(ass_id)
    return render(request, 'mainPage/about.html')

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib import messages


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

mainPage/templates/mainPage/about.html
{% extends "mainPage/base.html" %}
{% block content %}
    <h1>Main About</h1>
{% endblock content %}

mainPage/templates/mainPage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mainPage/main.css'%}">
    <title>Title</title>
</head>
<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Students Page</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'mainPage-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'mainPage-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>

      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script></body>
</body>
</html>

mainPage/templates/mainPage/class_choice.html
{% extends "mainPage/base.html" %}
{% block content %}
    <h1>List of Classes</h1>
    <div class="card mb-3">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Class</th>
                    <th>Attendance</th>
                </tr>
              </thead>
              <tbody>
                {% for ass in teacher.teaches_set.all %}
                {% if choice == 0 %}
                    <tr>
                        <td>{{ ass.classes }}</td>
                        <td><a class="btn btn-primary" href="{% url 'attendance_t' ass.id %}" role="button">Enter Attendance</a></td>
                    </tr>
                {% else %}
                    <tr>
                        <td>{{ ass.classes }}</td>
                        <td><a class="btn btn-primary" href="{% url 't_edit_attendance' ass.id %}" role="button">Edit Attendance</a></td>
                    </tr>
                {% endif %}
                {% empty %}
                        <p>teacher has no courses</p>
                {% endfor %}

              </tbody>
            </table>
          </div>
    </div>
{% endblock %}

mainPage/templates/mainPage/home.html
{% extends "mainPage/base.html" %}
{% block content %}
{#    <form action="/table/" method="post" id="systemForm">#}
{#    {% csrf_token %}#}
{#    {% for post in posts %}#}
{#        <button type="submit" name="system" form="systemForm" value={{ post.ClassChoice }}>{{ post.ClassChoice }}</button>#}
{#    {% endfor %}#}
{#    </form>#}
    <h1>For Students</h1>
    <div>
        <a class="btn btn-primary" role="button" href="{% url 'attendance' request.user.student.username %}"> View Attendance</a>
    </div>
    <div>
{#        <a class="btn btn-primary" role="button" href="{% url 'grades' request.user.student.USN %}"> View Grades</a>#}
    </div>

{% endblock content %}

mainPage/templates/mainPage/t_edit_attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mainPage/templates/mainPage/table.html
{% extends "mainPage/base.html" %}
{% block content %}
{#    <h1>for {{ system }}</h1>#}
{#    {% for syste in system %}#}
{#        <h1> {{ syste.username}} </h1>#}
{#        <p> {{ syste.first_name }} {{ syste.last_name }} </p>#}
{#    {% endfor %}#}
    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
        <strong>{{ cr.name }}</strong></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Day</th>
                    <th>Status</th>

                </tr>
              </thead>
              <tbody>
                    {% for value in att_list %}
                    <tr class="row100 body">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ value.date }}</td>
                        <td>{{ value.date|date:"l" }}</td>
                        {% if value.status == 0 %}
                        <td class="p-3 mb-2 bg-success text-white">Present <span class="glyphicon glyphicon-thumbs-up"></span></td>
                        {% elif value.status == 1 %}
                        <td class="p-3 mb-2 bg-danger text-white">Absent <span class="glyphicon glyphicon-thumbs-down"></span></td>
                        {% else %}
                        <td class="p-3 mb-2 bg-dark text-white">Late <span class="glyphicon glyphicon-thumbs-down"></span></td>
                        {% endif %}
                    </tr>
                {% empty %}
                        <p>student has no attendance</p>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
{% endblock content %}

mainPage/templates/mainPage/teacher_attendance_new_class.html
{% extends "mainPage/base.html" %}
{% block content %}

<form action="{% url 'submit_t' ass.id %}" method="post">
    {% csrf_token %}
    <label for="date">Enter Date: </label>
    <input type="date" name="date">

    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
            <b>{{ ass.classes_id }}</b>

        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Student name</th>
                    <th>Arrival Status</th>
                </tr>
              </thead>
                <tbody>
                {% for s in classes_taught.student_set.all %}
                    <tr>
                    <td>{{s.fullName}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.username }}" id="option1" autocomplete="off" value="present" checked> Present
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.username }}" id="option2" autocomplete="off" value="absent"> Absent
                                </label>

                                <label class="btn btn-outline-dark">
                                    <input type="radio" name="{{ s.username }}" id="option3" autocomplete="off" value="late"> Late
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>
{% endblock %}

users/templates/users/login.html
{% extends "mainPage/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "mainPage/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
{% endblock content %}

users/templates/users/register.html
{% extends "mainPage/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign Up</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
    </div>
{% endblock content %}